version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/express-mongoDB
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
