version: "3"
services:
  postgres-db:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres-nmp
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=node_rdb
      - POSTGRES_DB=node_rdb
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data-nmp

volumes:
  postgres_data:
